---
dist: trusty
sudo: required
language: cpp
compiler:
- gcc
- clang
before_install:
- sudo add-apt-repository -y ppa:kalakris/cmake
- sudo add-apt-repository -y ppa:samuel-bachmann/boost
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -qq -d update
install:
- sudo apt-get -qq install boost1.60 cmake g++-4.8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
script:
- bin/fetch-configlet
- bin/configlet .
- cmake -G "Unix Makefiles"
- make
